### PR TITLE
Support steam networking sockets and messages interfaces

### PR DESCRIPTION
**Pull request by Nonakesh**
It's still a bit rough around the edges, but it should be fairly usable at the current stage. I have one test case that successfully sends messages between a server and a client.

I would have liked to add a higher-level interface as well (like the UDP socket from std), but that would require per-socket callbacks and I wasn't sure how to implement that with the current system.

I started from the pull request by @garyttierney, but I had to make quite a few changes to work with the API.

### CODE REVIEW

**Comment by Nonakesh** [comment]
I just noticed I updated the doc-bindings somewhere along the line, I hope that's not a problem.

**Comment by garyttierney** [comment]
sorry, indeed I didn't get the chance to update my messages work! This looks pretty good. I'll get around to finishing the Messages interface sometime this week hopefully.

**Comment by Nonakesh** [comment]
No problem, I just didn't want to get in your way, but a few things were necessary for the sockets to work.

**Comment by Nonakesh** [comment]
Actually, I think I will partially rewrite it after all. I think I found a way of handling callbacks for multiple sockets and after seeing the `Friend` struct, I figured there was still a lot I could improve.

**Comment by Nonakesh** [comment]
I think this version is a lot more convenient to use. It's still a bit rough, but I think the most important functionality is there.
I tried getting it closer to the TCP sockets in std, with a few changes so all functions can still be used.

**Comment by Nonakesh** [comment]
@garyttierney I went ahead and implemented the messages interface as well.

I created functions for the callbacks, which is a bit inconsistent with the rest of the wrapper, but this way it's possible to make the API more convenient, in my opinion. For example, instead of returning the NetIdentity directly, the event returns a SessionRequest struct that can be used to accept or reject connections directly. 
Of course, I'd be happy to hear other opinions on this!

**Comment by Noxime** [comment]
Hey, sorry for taking so long to get to merging PRs. Whats the status of this code, is it ready for merging? I was thinking we could do a crates.io release after this lands, lots of nice changes have gathered up in the repo.

**Comment by Nonakesh** [comment]
Hey, no problem, life happens and all.

I'd say it's not perfect, ideally I would make some changes. For example I tried to keep each connection unique, but I think it might be less restrictive if there could be copies of each connection. A closed connection would return an Err, similar to the steamworks itself.
Also doc comments are missing all over the place.

But I don't really have time to make those changes right now and while it's not perfect, I tested it in a project of mine and it seems to work without problems.

**Comment by Noxime** [comment]
Thank you, its now merged. I think its better to have some API than no API at all. I think this is a good time to update the crates.io finally

**Pull request merged**
