### PR TITLE
Some fixes for NetworkMessages API

### PR DESCRIPTION
**Pull request by lucaspoffo**
Return callbacks handles for session request/failed.

Remove drop impl for SessionRequest, this was causing all sessions to be rejected

Add user-defined NetConnectionEnd. User can define their application-specific errors from a range, but this was causing panics if used. I caught this because NetworkMessages define 2 errors in this range ([1001, 1002](https://github.com/ValveSoftware/GameNetworkingSockets/blob/e0d33386903202d9af61e76d69c54e46ece2f457/src/steamnetworkingsockets/clientlib/csteamnetworkingmessages.cpp#L33)), I'm not sure why they used this values that should be application-specific errors.

### CODE REVIEW

**Comment by lucaspoffo** [comment]
Does this PR need any changes to move it forward? I can also add a simple example for the NetworkingMessage API if this would help.

**Comment by Nonakesh** [comment]
Hey, I made the pull request that added support for NetworkingMessages and NetworkingSockets.
I don't use networking messages myself, so it makes sense I missed some bugs in that part of the implementation.

I think your solution is not idiomatic, simply removing the drop makes it possible to leave a request open without giving an answer. In the NetworkingSockets API, I fixed the same problem by adding an is_handled field. It gets set to true when calling accept and prevents drop from rejecting the connection.

**Comment by lucaspoffo** [comment]
> Hey, I made the pull request that added support for NetworkingMessages and NetworkingSockets. I don't use networking messages myself, so it makes sense I missed some bugs in that part of the implementation, so thanks for cleaning up after me.
> 
> I think your solution is not idiomatic, simply removing the drop makes it possible to leave a request open without giving an answer. In the NetworkingSockets API, I fixed the same problem by adding an is_handled field. It gets set to true when calling accept and prevents drop from rejecting the connection.

Makes sense, I updated the PR with the copied logic from NetworkingSockets for the automatic reject request when not handled.

**Comment by lucaspoffo** [comment]
For the callback, I'm not sure if I should just save it inside the NetworkingMessages<Manager> struct.

**Comment by Nonakesh** [comment]
Yes, I think saving the callback handles in the struct is probably best. I don't remember what they are used for, but I definitely wouldn't return the handle. That's part of the internal implementation, so ideally it shouldn't be necessary to have it.

**Pull request closed without merging**
