### PR TITLE
Add lobby list request filtering

### LINKED ISSUE #140: Wrappers for lobby list request filtering
Add wrappers for the following functions: 
- [ISteamMatchmaking::AddRequestLobbyListStringFilter](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListStringFilter) - Adds a string comparison filter.
- [ISteamMatchmaking::AddRequestLobbyListNumericalFilter](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListNumericalFilter) - Adds a numerical comparison filter.
- [ISteamMatchmaking::AddRequestLobbyListNearValueFilter](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListNearValueFilter) - Sorts the results closest to the specified value.
- [ISteamMatchmaking::AddRequestLobbyListFilterSlotsAvailable](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListFilterSlotsAvailable) - Filters to only return lobbies with the specified number of open slots available.
- [ISteamMatchmaking::AddRequestLobbyListDistanceFilter](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListDistanceFilter) - Sets the physical distance for which we should search for lobbies, this is based on the users IP address and an IP location map on the Steam backed.
- [ISteamMatchmaking::AddRequestLobbyListResultCountFilter](https://partner.steamgames.com/doc/api/ISteamMatchmaking#AddRequestLobbyListResultCountFilter) - Sets the maximum number of lobbies to return. The lower the count the faster it is to download the lobby results & details to the client.

I propose having one `set_lobby_list_filter` function that takes a struct with all these options. I can work on this and hopefully have a PR by today

### PR DESCRIPTION
**Pull request by wyvernbw**
closes #140 
# Summary
added 7 functions for filtering out lobby requests:
* `set_lobby_list_filter`: adds filters defined in a `LobbyListFilter` struct.
* `set_request_lobby_list_string_filter`: adds filters for key value pairs of strings.
* `set_request_lobby_list_numerical_filter`: adds filters for key value pairs of string number types.
* `set_request_lobby_list_near_value_filter`: adds sorting based on which value is closer to the filter
* `set_request_lobby_list_distance_filter`: adds filtering based on geographical distance
* `set_request_lobby_list_slots_available_filter`: adds filtering based on how many open slots a lobby has
* `set_request_lobby_list_result_count_filter`: adds the maximum number of results a request can resolve to.

added 1 struct:
* `LobbyListFilter`: struct that holds every option possible for filtering

added 1 enum: 
* `DistanceFilter`: thin wrapper over `ELobbyDistanceFilter`
I included documentation for everything I added and one code example.

### CODE REVIEW

**Comment by wyvernbw** [comment]
I omitted comparison types for the filters as they don't seem very useful imho. I'm open to changing this, ofc

**Comment by TrustNoOneElse** [comment]
First pretty cool that you are working on this!

I just wanted to note that you can have a List/Array of String-, Numeric- and NearValueFilters, that why i would update the LobbyListFilter struct to actually support it. 

Another point on which im not certain about but the `key`of those filters cannot exceed 255 chars. For setting the metadata of a lobby the function itself already returns a bool, if thats the case. In this case of the filter functions, we could maybe implement a safety check for the user, because he may be not aware of this or to add this to the docs.

**Comment by wyvernbw** [comment]
Thanks for the kind words!

I didnt know you can pass in multiple key value pairs, i assumed you have to call the function multiple times. Is this done by passing a pointer to the array to the underlying steamworks-sys call? 

I just checked and you are correct, you can only pass in keys shorter than 256 characters

**Comment by TrustNoOneElse** [comment]
That is correct, you have to call the function multiple times. What i meant was your helper type `LobbyListFilter`, which currently only suppports one times of String, Numeric and Nearfilters. Thats why i would suggest the change to take in a Array of key/value pairs for this 3 types of filter.

And to the comparison types:
For String i can't see the use too, besides Equal and NotEqual and i also doesn't know anyone which used besides this two comparision types anything. But for numeric you can do quite a lot with this things.
Some examples:
NotEqual: Could be a metadata with a playerid matched against last time, so you could filter out that they don't play again, to have variation.
For the other cases (Greater then, Less Then, Equal Less, Equal Greater), the best example is level matchmaking or elo/skill matchmaking.

**Comment by wyvernbw** [comment]
Ok so turns out `&[T]` cannot be deserialized in serde. At least i can't figure out how. So i just went ahead and changed it to use `Vec`. A more performant (i think) would be `Arc<[T]>` but that would require the `rc` feature in serde

**Pull request merged**
