### PR TITLE
Enable local builds with SDK and add CI

### PR DESCRIPTION
**Pull request by james7132**
This is a potentially contentious change that adds the following:

 - Continuous integration to build the library via GitHub Actions
 - **Embeds the bound Steamworks SDK under lib/steam**
 - Adds a `.cargo` directory and config that links to the SDK, injecting the `STEAM_SDK_LOCATION` env variable at build time.

This enables local builds from the git repo without needing to fetch the SDK separately, though crates.io downloads will still have to, and enables continuous integration checks via GitHub Actions.

The main issue that might arise is the redistribution of the Steamworks SDK. I'm not sure if this runs afoul of the Steamworks SDK license or is incompatible with the MIT/Apache license of `steamworks-rs`, but other SDK wrappers like [Steamworks.NET](https://steamworks.github.io/installation/) and [Facepunch.Steamworks](https://wiki.facepunch.com/steamworks/Installing_For_Unity) seems to do this, at least for Unity. 

cc. @Noxime @ceifa: Definitely want opinions from both of you before merging this in any form.

### CODE REVIEW

**Comment by ceifa** [comment]
These test will actually work inside a github action?
I'm not sure but I think it needs to have Steam installed to succeed.

**Comment by james7132** [comment]
Still testing it. If it doesn't work, we can always just ensure that it builds with `cargo build` instead.

**Comment by adumbidiot** [comment]
> The main issue that might arise is the redistribution of the Steamworks SDK. I'm not sure if this runs afoul of the Steamworks SDK license or is incompatible with the MIT/Apache license of steamworks-rs, but other SDK wrappers like [Steamworks.NET](https://steamworks.github.io/installation/) and [Facepunch.Steamworks](https://wiki.facepunch.com/steamworks/Installing_For_Unity) seems to do this, at least for Unity.

According to the [SDK Access Agreement](https://partner.steamgames.com/documentation/sdk_access_agreement), users are allowed to
> reproduce and distribute the part of the SDK provided inside the folder named redistributable_bin (the "SDK Redistributables") along with the Licensee Software in object code form.

This folder includes all DLLs and LIB files necessary for compilation, so while I think simply uploading the entire SDK is prohibited, we can upload the `redistributable_bin` folder so we can compile and run without the user needing to setup the Steamworks SDK. However, I don't think uploading headers is allowed so would have to pre-generate bindings.

**Comment by james7132** [comment]
If that's the case, I think we should just:
 
 - Remove the headers from this PR.
 - Add a `CONTINUOUS_INTEGRATION` env-var flag to avoid bindgen code generation during CI builds.
 - Add a clause to the .gitignore to avoid checking in the headers into git.
 - Squash out the headers during the merge.
 - Delete the branch from my fork.

**Comment by adumbidiot** [comment]
Sounds good, but I think the license only will let us upload, or redistribute, the `redistributable_bin` folder. So if we put stuff into a .gitignore, it would have to ignore everything except the contents of that folder.

**Comment by ceifa** [comment]
Because the bindings file is static, maybe we can change the default behavior to just copy it from the `src` folder to the output. That way we can remove the need of `STEAM_SDK_LOCATION` completely.

**Comment by adumbidiot** [comment]
Since it looks like this library supports only targeting one version of the Steamworks SDK, I don't really see the need of the `STEAM_SDK_LOCATION` if we bundle the `redistributable_bin` folder. All we would need to do is pre-generate the bindings for each new Steamworks release.  [Rusqlite](https://github.com/rusqlite/rusqlite) also chooses to ship pre-generated bindings, so  maybe we could use it for inspiration.

**Comment by james7132** [comment]
I should note that distributing via crates.io/cargo does not allow us to include binaries in the package. Anyone installing it from there will still have to specify it manually.

**Comment by adumbidiot** [comment]
> I should note that distributing via crates.io/cargo does not allow us to include binaries in the package. Anyone installing it from there will still have to specify it manually.

Do you have a source for that? I remember seeing some crates like [sodiumoxide](https://github.com/sodiumoxide/sodiumoxide) that do exactly that.

**Comment by james7132** [comment]
@adumbidiot, you were right, I was mistaken. Read somewhere saying that cargo/crates.io was a source distribution system and apparently mistook that to mean it doesn't support binaries. Tested it with `cargo package` and turns out it does indeed work. Made the following changes:

 - Removed the headers **BE SURE TO SQUASH THE MERGE FOR THIS PR OR THIS WILL BE IN THE REPO'S HISTORY**.
 - Added `lib/steam` to the gitignore, and counter gitignored `lib/steam/redistributable_bin`.
 - Replaced `docs-only` with `rebuild-bindings`. This has an added benefit that `bindgen` is now optional and only required if you are rebuilding bindings.
 - Not rebuilding bindings will still copy the SDK dll/so files to the final output directory.
 - Updated the README to remove the bindgen and env-var requirements, as this will be automatically handled by the `.cargo` config included in the packaged crate.
 - Rebuilding bindings and packaging/publishing the crate for crates.io still requires the headers. Probably a good sanity check and will really only be needed by maintainers and others developing this crate.

**Review by ceifa — APPROVED** [review]

**Comment by adumbidiot** [comment]
> Read somewhere saying that cargo/crates.io was a source distribution system and apparently mistook that to mean it doesn't support binaries.

Yeah I read that too, but I don't think that its strictly enforced anywhere. The alternative would be making users download the steam sdk just to get those binary files, which I thought would make little sense, especially since I know of a few crates that bundle binaries. 

> Updated the README to remove the bindgen and env-var requirements, as this will be automatically handled by the .cargo config included in the packaged crate.

I don't think this file is applied when it is not in the top-level crate. As a result, I don't think the build script will run for users who don't explicitly set this variable; the build script expects this variable to always be set, regardless of whether `bindgen` is run or not.

**Comment by james7132** [comment]
> I don't think this file is applied when it is not in the top-level crate. As a result, I don't think the build script will run for users who don't explicitly set this variable; the build script expects this variable to always be set, regardless of whether `bindgen` is run or not.

Confirmed this is the case, removed the `.cargo` config, made the `STEAM_SDK_LOCATION` env var optional and then used `CARGO_MANIFEST_DIR` which is always available, and moved the `lib` folder into steamworks-sys to ensure it's included when packing it for redistribution.

**Comment by ceifa** [comment]
LGTM, what you think @adumbidiot?

**Pull request merged**
