### PR TITLE
Shut up compiler warning

### PR DESCRIPTION
**Pull request by ry00001**
I noticed a compiler warning. This quietens it. (Blame dead-code analysis not working for debug.)

### CODE REVIEW

**Comment by ry00001** [comment]
Wait fuck, this pulls in the commits from #92 too. It's already merged though...?

**Comment by james7132** [comment]
Can you rebase this onto `master`?

**Comment by ry00001** [comment]
How would I do that? I don't have much PR experience, sorry.

**Comment by james7132** [comment]
Pull down the latest master branch onto your local master branch, `git merge master` while on this branch.

**Comment by ry00001** [comment]
I did that - no pushes went out on git though

**Pull request merged**
