### PR TITLE
Update SDK to 1.57

### PR DESCRIPTION
**Pull request by Elanis**
This PR updates method to be compatible with Steamworks SDK 1.57.

**ISteamUser:GetAuthSessionTicket** now requires SteamNetworkingIdentity as parameter:
 - I updated existing methods to take this change in account. `user.authentication_session_ticket` now needs a NetworkingIdentity as parameter
 - I added an alternative method, which can be used only with a steam id `user.authentication_session_ticket_with_steam_id`
 - I updated tests for this new use case (and renamed it to `test_auth_dll()`, see why in the following text).

Same changes for **ISteamGameServer:GetAuthSessionTicket**

There's now a method called **ISteamUser:GetAuthTicketForWebApi** used for generating WebAPI checked tickets. 
It has been exposed by `user.authentication_session_ticket_for_webapi()`.
A callback event `GetTicketForWebApiResponse_t` is used after this ticket creation, it's catched by Rust using `TicketForWebApiResponse`.

This whole process is tested by `test_auth_webapi()` method.

---

This PR has been tested by unit tests and on my Tauri game (both on Windows). And I ran CI to check if every symbol was okay.

Feel free to review anything that might look wrong in it. It's my first time binding some C stuff in Rust !

### CODE REVIEW

**Comment by ceifa** [comment]
Note: This is a breaking change

**Comment by Elanis** [comment]
I found an UB in my PR when casting to C's `const char *`, just commited a fix for it :)

**Comment by Elanis** [comment]
(Rebased on latest master)

**Comment by Noxime** [comment]
Thank you for the pull request!

**Comment by Elanis** [comment]
You're welcome !
Happy to participate in this cool project :)

**Comment by flyinghail** [comment]
I tested and found that `SteamAPI_SteamUGC_v016` needs to be renamed to `SteamAPI_SteamUGC_v017`, otherwise it fails to compile. I don't know if it's just me or not.

**Comment by flyinghail** [comment]
> Did you use 1.57 ? Because 1.58 just released a week ago and they changed UGC parts. So I think that's your issue :)

I copied the sdk file from the main branch, which should still be 1.57.

**Comment by kristoff3r** [comment]
It seems like they changed 1.57 after the fact, I get the same error if I try to rebuild bindings from 1.57.

**Pull request merged**
