### PR TITLE
Update bindings

### PR DESCRIPTION
**Pull request by cozyGalvinism**
As mentioned in #100 , these are the new bindings. You *should* be able to reproduce these changes by doing the following:

1. Download the newest version of the Steamworks SDK (1.53a in this case)
3. `cd steamworks-sys`
4. Delete the `public` and `redistributable_bin` folders from `lib/steam`
5. Unpack the SDKs' `public` and `redistributable_bin` folders into `lib/steam`
6. `cargo clean` (might not be necessary if you pulled from scratch, if you didn't, there is a high likelihood that the bindings are **not** regenerated! I've had that happening)
7. `cargo build --features rebuild-bindings`

This is a fairly large diff, so I hope it doesn't break anything.

Seemingly the bindings now feature various `packed` reprs and more changes.

### CODE REVIEW

**Comment by ceifa** [comment]
The steamworks SDK v1.54 just got released! Maybe we can upgrade to it directly.

**Comment by cozyGalvinism** [comment]
I will check really quick :D

**Comment by james7132** [comment]
It seems like the bindings generated are different depending on which platform you're using. I bound against v153a on Windows when generating those bindings. A quick look at the generated code seems to have #define variables that correspond to Linux. We may need to have platform specific bindings in the repo.

**Comment by cozyGalvinism** [comment]
> It seems like the bindings generated are different depending on which platform you're using. I bound against v153a on Windows when generating those bindings. A quick look at the generated code seems to have #define variables that correspond to Linux. We may need to have platform specific bindings in the repo.

That makes sense... Would definetly explain the issues I have faced, if the bindings that are in currently were made on a Windows PC... though I guess another way would be to introduce build caching and let the bindings be generated once for a version via build script. As the Steamworks SDK provides redistributables, this could also solve the issue, but increases the crate size and probably pumps up the first compile time by a fair amount.

**Comment by cozyGalvinism** [comment]
> It seems like the bindings generated are different depending on which platform you're using. I bound against v153a on Windows when generating those bindings. A quick look at the generated code seems to have #define variables that correspond to Linux. We may need to have platform specific bindings in the repo.
> 
> Happy to approve the new v154 bindings when made available, but we likely need a separate PR to split the bindings based on target.

Hmm... Are the bindings different if you just change the target? Or are they only different if they're built on Windows/Mac/Linux? That result would change the way the new PR would have to be implemented.

**Comment by cozyGalvinism** [comment]
Alright, I created #105 for v1.53a platform-specific bindings and #106 for v1.54 platform-specific bindings

**Comment by cozyGalvinism** [comment]
Closing this in favor of #106

**Pull request closed without merging**
